# Copyright 2020 Redpanda Data, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: Lint all codez
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  go:
    name: Lint go files
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.8

    - name: lint rpk
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45.2
        working-directory: src/go/rpk/

    - name: install gofumpt
      working-directory: src/go/rpk
      run: |
        go install mvdan.cc/gofumpt@v0.3.0

    - name: lint go files
      working-directory: src/go
      run: |
        find . -name *.go -type f | xargs -n1 gofumpt -w -lang=1.17
        git diff --exit-code

  js:
    name: Lint js files
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12.16.1'

    - name: Set up prettier
      run: npm install prettier@2.3.0

    - name: Lint JS files
      run: npx prettier --list-different src/**/*.{ts,js}

  py:
    name: Lint python files
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up python
      run: |
        sudo apt-get install -y python3 python3-pip
        sudo pip install yapf==0.30.0

    - name: lint python files
      run: find . -name *.py -type f | xargs -n1 yapf -d

  cpp:
    name: Lint files with clang-format
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run clang-format
      run: |
        find . -type f -regex '.*\.\(cpp\|h\|hpp\|cc\|proto\|java\)' | xargs -n1 clang-format-12 -i -style=file -fallback-style=none
        git diff --exit-code

  sh:
    name: Lint shell scripts
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install shfmt
      env:
        SHFMT_VER: 3.5.1
      run: |
        mkdir -v -p "$HOME/.local/bin"
        wget -O "$HOME/.local/bin/shfmt" "https://github.com/mvdan/sh/releases/download/v${SHFMT_VER}/shfmt_v${SHFMT_VER}_linux_amd64"
        chmod 0700 "$HOME/.local/bin/shfmt"

    - name: Run shfmt
      run: shfmt -i 2 -ci -s -d .
