name: old-backports
on:
  schedule:
    - cron: '*/10 * * * *'
env: 
  OUTPUT: $(gh search issues --label "kind/backport" --state open --repo "redpanda-data/redpanda" --updated "<`date --date="15 days ago" +"%Y"-"%m"-"%d"`" --sort updated --order asc --limit 15 --json "assignees,updatedAt,url" --jq '.[] | "@" + (.assignees[] | {login} | .login), .url, .updatedAt,"----"')
  
jobs:
  alert-on-abandoned-backports:
    name: Post Slack Message
    runs-on: ubuntu-latest
    steps:

    - name: "Post to a test channel (temporary)"
      id: send-slack-message
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: "C05DHDW4VCL"
        slack-message: "Test: ${{ env.OUTPUT }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.VBOTBUILDOVICH_SLACK_BOT_TOKEN }}
